CopyData = $00b1
PrintBCDNumber_loop = $13bf
JoypadLowSensitivity = $381e
Multiply = $38a5
Divide = $38b2
BankswitchCommon = $3e7e
DisplayNamingScreen = $016307
Audio1_MultiplyAdd = $02581f
FlagAction = $0374ef
wBuffer = $cf4a
wNamingScreenType = $d07c

hMultiplicand = $ff96
hMultiplier = $ff99
hJoy5 = $ffb5

NAME_MON_SCREEN = 2
FRAG_BANKSWITCH_BANK1 = $1135
FRAG_BANKSWITCH_BANK3 = $074b
FRAG_ASKNAME_AFTERTEXTBOX = $016295

WRITE_DESTINATION = $da82

.global Rabootstrapper
.global WriteMore
.global Encoder1
